services:
  github-backup:
    build: .
    container_name: github-backup-container
    volumes:
      - ./backups:/backups
      - ./.env:/app/.env:ro
    ports:
      - "3007:3007"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BACKUP_DIR=/backups
      - PORT=3007
    restart: unless-stopped
    labels:
      - "com.unraid.container.icon=https://github.com/fluidicon.png"
      - "com.unraid.container.name=GitHub Backup"
      - "com.unraid.container.description=Automated GitHub repository backup solution"

volumes:
  github_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BACKUP_DIR}
